### ISSUE TITLE
Card pada slide.

### ISSUE THREAD

**Issue by feri-irawan** [bellshade/bellshade.github.io#12]
- [x] Isi modal card yang kosong jika tombol *Let's Go!* pada card di klik
- [x] Tampilan modal card yang tertutup oleh navbar karna kurang ke bawah [SOLVED]

**Comment by hendraaagil** [comment]
Lebih baik dibikin checklist aja daripada cuma list
Misal:
- [x] List 1
- [ ] List 2

Markdownnya:
```
- [x] List 1
- [ ] List 2
```

**Comment by feri-irawan** [comment]
> Lebih baik dibikin checklist aja daripada cuma list
> Misal:
> 
> * [x]  List 1
> * [ ]  List 2
> 
> Markdownnya:
> 
> ```
> - [x] List 1
> - [ ] List 2
> ```

Siap om.. makasi sarannya

**Comment by reacto11mecha** [comment]
Kayaknya issue ini seharusnya udah bisa di close

Alasan
- https://github.com/bellshade/bellshade.github.io/commit/788d705140ebbf53c0c9d3b24a69e6760ea190bc revisi dari commit sebelumnya gara-gara kode yang sebelumnya card dipencet ga muncul modalnya
- https://github.com/bellshade/bellshade.github.io/commit/b4f6dafd4394b143632a839a4d3cd5b235550548 diubah z index dari si modal biar ga mentok navbar

**Comment by feri-irawan** [comment]
Siap!
