### ISSUE TITLE
Konsistensi kode

### ISSUE THREAD

**Issue by hendraaagil** [bellshade/bellshade.github.io#13]
Di project ini kita menggunakan 2 cara styling:

1. Custom SCSS
2. Tailwind CSS

Menurut saya lebih baik kita jadiin 1 cara aja, mau pakai Tailwind CSS / SCSS aja supaya ga bikin bingung
Berhubungan dengan: https://github.com/bellshade/bellshade.github.io/issues/11#issuecomment-916768780

Mari berdiskusi 👌

**Comment by hendraaagil** [comment]
Oh iya satu lagi, menurut saya kita ga perlu pake jQuery 😅

**Comment by reacto11mecha** [comment]
Kalo boleh saran, migrasi ke vite aja. Purge css bisa kepake buat mangkas css nya si tailwind

**Comment by nomadkode** [comment]
> Kalo boleh saran, migrasi ke vite aja. Purge css bisa kepake buat mangkas css nya si tailwind

nah boleh juga nih pake vite, wise choice

**Comment by yezki** [comment]
Kesimpulan sementara :

- Drop custom CSS & SCSS, pakai Tailwind aja.
- Drop jQuery.
- Migrasi ke vite.

**Comment by nomadkode** [comment]
ada yg mau mulai implementasi kah?

**Comment by reacto11mecha** [comment]
Mau di init vite nya ?

**Comment by nomadkode** [comment]
> Mau di init vite nya ?

gasss zra. mau init aja apa ngubah kode juga?

**Comment by reacto11mecha** [comment]
Kayaknya sih ngikutin yang saat ini, mindahin jquery ke vite nya + config purgecss

**Comment by nomadkode** [comment]
> Kayaknya sih ngikutin yang saat ini, mindahin jquery ke vite nya + config purgecss

boleh zra, nanti PR aja trus di review sm temen2 web

**Comment by reacto11mecha** [comment]
> > Kayaknya sih ngikutin yang saat ini, mindahin jquery ke vite nya + config purgecss
> 
> boleh zra, nanti PR aja trus di review sm temen2 web

Siap
