### ISSUE TITLE
Team Card masih rata kiri

### ISSUE THREAD

**Issue by yezki** [bellshade/bellshade.github.io#25]
Sebaiknya Team Cardnya dibikin rata tengah agar nyaman diliat.

![135236344-14b52cc6-f4fa-4691-9364-a6e8a05cede8](https://user-images.githubusercontent.com/54763039/135377068-7c310897-43a6-4616-bab1-9038651d8cba.png)
![135061302-0c74cb60-e2f0-4f83-b583-8ea9a8a720dc](https://user-images.githubusercontent.com/54763039/135377087-f69fa31e-f857-45c4-95a3-0ccd1b52e785.png)

**Comment by ahmadmcer** [comment]
Izin bertanya, maksud biar rata tengah gimana yah?

**Comment by nomadkode** [comment]
@bellshade/webpage-team siapa yang mau handle issue ini?
