### ISSUE TITLE
untuk beberapa breakpoint di mobile device heading h1 ketutupan 

### ISSUE THREAD

**Issue by aryawirasandi** [bellshade/bellshade.github.io#34]
![image](https://user-images.githubusercontent.com/23094818/135784570-43146995-150c-4d64-857b-3925dab52146.png)
pas buka breakpoint pixel 2, iphone SE sama iphone 6 untuk kalimat "Learn with our communitynya ketutupan"
![image](https://user-images.githubusercontent.com/23094818/135784778-e4a356ff-4b02-4066-9f22-e1f30378406f.png)

**Comment by nomadkode** [comment]
ini yaa @elvinafirmansyah @kingramzy
