### ISSUE TITLE
js framework ?

### ISSUE THREAD

**Issue by sap471** [bellshade/bellshade.github.io#36]
kenapa enggak memakai js framework yang terkenal misalnya vue atau react ?

pertimbangan nya sebagai berikut :
- supaya penataan componentnya lebih rapi dan jelas 
- dynamic component dan dynamic routes jika diperlukan
- untuk dokumentasi pembelajaran bisa memakai markdown
- untuk saat deploy bisa menggunakan static files

**Comment by nomadkode** [comment]
halo @sap471 terima kasih atas sarannya, tapi untuk sementara implementasi web bellshade di versi 1.0 hanya menggunakan tech seperti tailwind, vite.js dan sisanya vanilla html-css. kami sudah memiliki rencana migrasi ke versi 2.0 menggunakan framework javascript.

Terima kasih atas sarannya.

cc: @bellshade/webpage-team

**Comment by mzaini30** [comment]
Apakah issue ini perlu diclose?

**Comment by sap471** [comment]
rencananya mau make framework apa mas @nomadkode ?
atau udah dikembangin versi 2.0 nya ?

**Comment by nomadkode** [comment]
> rencananya mau make framework apa mas @nomadkode ?
> atau udah dikembangin versi 2.0 nya ?

Untuk teknologi JavaScript yang dipakai belum ada diskusi yang fix yaa, baru hanya ada keinginan dari tim saja untuk memakai teknologi tertentu.

Untuk saat ini bellshade secara umum dan tim web secara khusus masih fokus di pengembangan versi 1.

Terima kasih atas perhatiannya.

**Comment by nomadkode** [comment]
> Apakah issue ini perlu diclose?

Boleh om zen. 🤙🏻

**Comment by LevianthProject** [comment]
I appreciate your idea but these ideas cannot be accepted and this repository is only for the internal team.
Thank you for your response.
