### ISSUE TITLE
English on feature request template

### ISSUE THREAD

**Issue by mazipan** [bellshade/bellshade.github.io#41]
## Deskripsi

Maaf ada komentar yang terlewat di `.github/ISSUE_TEMPLATE/feature_request.md` dari hasil pr di #38 masih menggunakan bahasa Inggris

## Perilaku yang diharapkan

Seharusnya diterjemahkan ke bahasa Indonesia

**Comment by nomadkode** [comment]
> Mohon bantuannya dari yang lain untuk bantu menterjemahkan dan memperbaiki tulisannya 🙏

siap mas @mazipan akan diperbaiki segera
