### ISSUE TITLE
Timeout access bellshade.org

### ISSUE THREAD

**Issue by mazipan** [bellshade/bellshade.github.io#71]
## Deskripsi

Timeout ketika mengakses https://bellshade.org/

## Tangkapan layar

![Screen Shot 2021-11-29 at 11 36 42](https://user-images.githubusercontent.com/7221389/143809767-b146a9ff-fe34-431f-a728-f00bc6e19351.png)

**Comment by dipras** [comment]
Dah di fixed ya Maz Ipan :D
